version: "3.9"

services:
  passer_frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: passer_frontend
    image: passer_frontend:prod
    restart: always
    ports:
      - 8080:80
