version: "3.9"

services:
  passer_frontend:
    build:
      target: dev
    image: passer_frontend:dev
    ports:
      - 5173:5173
    volumes:
      - ./app:/home/app
      - /home/app/node_modules
