name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build --target prod  -f app/Dockerfile -t passer:prod ./app/

      - name: Create Artifacts Directory
        run: mkdir -p ./artifacts

      - name: Copy Artifacts From Docker Image
        run: docker create --name tmp-container passer:prod && docker cp tmp-container:/usr/share/nginx/html ./artifacts && docker rm tmp-container

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: artifacts/html # The folder the action should deploy.
